In [4]:
#PANDAS
#Main Theme of Pandas, ex:If we hava Dataset with 10 Records it's very easy to analysis and manipulations(changes).
#In case we have 1000000 record Dataset,then it's difficult to analysis and manipulation,then in that case we use pandas.
#What is Dataset:Large or samll amount of Data with tabular format is known as "Dataset"
#Creating DataFrame:
#Load the Data from "Excel File"
#read_excel("File_Location")
#Load the Data from "CSV File"
#read_CSV("File_Location"

In [5]:
#Load the Data from "Excel File"
#read_excel("File_Location") Here we can use the "read_excel" function to load the data from excel file.

In [6]:
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df

,Unnamed: 0,Roll number,Name,Maths,Telugu,Science,Social,English
0,0,101,sai,90,87,90,70,89
1,1,102,manoj,98,67,87,89,78
2,2,103,pradeep,87,85,69,85,72
3,3,104,giri,67,93,90,92,83
4,4,105,vishnavi,78,92,89,78,94
5,5,106,teju,88,87,82,96,93
6,6,107,teja sree,86,75,91,95,94
7,7,108,mahi,87,90,94,93,95
8,8,109,mani,80,97,95,94,96
9,9,110,charan,90,92,96,90,97
10,10,111,pavan,89,91,89,92,98
11,11,112,kiran,98,76,93,89,99
12,12,113,harsha,91,90,92,90,82
13,13,114,bhuvi,94,90,90,87,93
14,14,115,hemanth,93,87,90,82,72
15,15,116,hari,82,85,72,99,74
16,16,117,kalyan,81,89,93,81,76
17,17,118,revanth,83,96,91,82,67
18,18,119,keerthna,78,92,87,93,90

In [7]:
#DataFrames 1:
#data_frame.head(number of rows)

In [8]:
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df.head(3)

   Unnamed: 0  Roll number     Name  Maths  Telugu  Science  Social  English
0           0          101      sai     90      87       90      70       89
1           1          102    manoj     98      67       87      89       78
2           2          103  pradeep     87      85       69      85       72

In [9]:
#DataFrames 2:
#data_frame.tail(number of rows)

In [10]:
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df.tail(4)

    Unnamed: 0  Roll number      Name  Maths  Telugu  Science  Social  English
15          15          116      hari     82      85       72      99       74
16          16          117    kalyan     81      89       93      81       76
17          17          118   revanth     83      96       91      82       67
18          18          119  keerthna     78      92       87      93       90

In [11]:
#DataFrames 3:
#data_frame.describe() --- It will give the statistical information about the data in the DataFrame.

In [12]:
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df.describe()

,Unnamed: 0,Roll number,Maths,Telugu,Science,Social,English
count,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000
mean,9.000000,110.000000,86.315789,87.421053,88.421053,88.263158,86.421053
std,5.627314,5.627314,7.623448,7.485659,7.081398,7.132415,10.404677
min,0.000000,101.000000,67.000000,67.000000,69.000000,70.000000,67.000000
25%,4.500000,105.500000,81.500000,86.000000,88.000000,83.500000,77.000000
50%,9.000000,110.000000,87.000000,90.000000,90.000000,90.000000,90.000000
75%,13.500000,114.500000,90.500000,92.000000,92.500000,93.000000,94.500000
max,18.000000,119.000000,98.000000,97.000000,96.000000,99.000000,99.000000

In [13]:
#DataFrames 4:
#data_frame.shape--- It will give the number of rows and columns in the DataFrame.

In [14]:
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df.shape

(19, 8)

In [15]:
#DataFrames 5:
#data_frame[start:stop;step]--- It will give the data from start to stop with step.

In [16]:
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df[0:10:2]

   Unnamed: 0  Roll number       Name  Maths  Telugu  Science  Social  English
0           0          101        sai     90      87       90      70       89
2           2          103    pradeep     87      85       69      85       72
4           4          105   vishnavi     78      92       89      78       94
6           6          107  teja sree     86      75       91      95       94
8           8          109       mani     80      97       95      94       96

In [17]:
#DataFrames 6:
#data_frame['column_name']--- It will give the data of that column.

In [18]:
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df['Name']

0           sai
1         manoj
2       pradeep
3          giri
4      vishnavi
5          teju
6     teja sree
7          mahi
8          mani
9       charan
10        pavan
11        kiran
12       harsha
13        bhuvi
14      hemanth
15         hari
16       kalyan
17      revanth
18     keerthna
Name: Name, dtype: object

In [19]:
#DataFrames 7:
#data_frame[['column_name1','column_name2']]--- It will give the data of those columns.

In [20]:
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df[['Roll number','Name']]

    Roll number       Name
0           101        sai
1           102      manoj
2           103    pradeep
3           104       giri
4           105   vishnavi
5           106       teju
6           107  teja sree
7           108       mahi
8           109       mani
9           110    charan
10          111      pavan
11          112      kiran
12          113     harsha
13          114      bhuvi
14          115    hemanth
15          116       hari
16          117     kalyan
17          118    revanth
18          119   keerthna

In [21]:
#DataFrames 8:
#data_frame[['column_name1','column_name2']][start:stop;step]--- It will give the data of those columns from start to stop with step.

In [22]:
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df[['Name','Maths']][0:10:1]

        Name  Maths
0        sai     90
1      manoj     98
2    pradeep     87
3       giri     67
4   vishnavi     78
5       teju     88
6  teja sree     86
7       mahi     87
8       mani     80
9    charan      90

In [23]:
#DataFrames 9:
#data_frame.iterrows()--- It will give the data of each row in the DataFrame.

In [24]:
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx") 
for index, row in df.iterrows():
    print(row)

Unnamed: 0       0
Roll number    101
Name           sai
Maths           90
Telugu          87
Science         90
Social          70
English         89
Name: 0, dtype: object
Unnamed: 0         1
Roll number      102
Name           manoj
Maths             98
Telugu            67
Science           87
Social            89
English           78
Name: 1, dtype: object
Unnamed: 0           2
Roll number        103
Name           pradeep
Maths               87
Telugu              85
Science             69
Social              85
English             72
Name: 2, dtype: object
Unnamed: 0        3
Roll number     104
Name           giri
Maths            67
Telugu           93
Science          90
Social           92
English          83
Name: 3, dtype: object
Unnamed: 0            4
Roll number         105
Name           vishnavi
Maths                78
Telugu               92
Science              89
Social               78
English              94
Name: 4, dtype: object
Unnamed: 0        5
Roll number     106
Name           teju
Maths            88
Telugu           87
Science          82
Social           96
English          93
Name: 5, dtype: object
Unnamed: 0             6
Roll number          107
Name           teja sree
Maths                 86
Telugu                75
Science               91
Social                95
English               94
Name: 6, dtype: object
Unnamed: 0        7
Roll number     108
Name           mahi
Maths            87
Telugu           90
Science          94
Social           93
English          95
Name: 7, dtype: object
Unnamed: 0        8
Roll number     109
Name           mani
Maths            80
Telugu           97
Science          95
Social           94
English          96
Name: 8, dtype: object
Unnamed: 0           9
Roll number        110
Name           charan
Maths               90
Telugu              92
Science             96
Social              90
English             97
Name: 9, dtype: object
Unnamed: 0        10
Roll number      111
Name           pavan
Maths             89
Telugu            91
Science           89
Social            92
English           98
Name: 10, dtype: object
Unnamed: 0        11
Roll number      112
Name           kiran
Maths             98
Telugu            76
Science           93
Social            89
English           99
Name: 11, dtype: object
Unnamed: 0         12
Roll number       113
Name           harsha
Maths              91
Telugu             90
Science            92
Social             90
English            82
Name: 12, dtype: object
Unnamed: 0        13
Roll number      114
Name           bhuvi
Maths             94
Telugu            90
Science           90
Social            87
English           93
Name: 13, dtype: object
Unnamed: 0          14
Roll number        115
Name           hemanth
Maths               93
Telugu              87
Science             90
Social              82
English             72
Name: 14, dtype: object
Unnamed: 0       15
Roll number     116
Name           hari
Maths            82
Telugu           85
Science          72
Social           99
English          74
Name: 15, dtype: object
Unnamed: 0         16
Roll number       117
Name           kalyan
Maths              81
Telugu             89
Science            93
Social             81
English            76
Name: 16, dtype: object
Unnamed: 0          17
Roll number        118
Name           revanth
Maths               83
Telugu              96
Science             91
Social              82
English             67
Name: 17, dtype: object
Unnamed: 0           18
Roll number         119
Name           keerthna
Maths                78
Telugu               92
Science              87
Social               93
English              90
Name: 18, dtype: object

In [25]:
#DataFrames 10:
#data_frame loc[]--- It will give the data of that row in the DataFrame.
#About iloc: In python we learn,during indexing,stop index is not included, but in case of iloc,stop index is included. 
#Finalliy, we can say that loc means stop index is included.

In [26]:
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df.loc[0:5:1]

   Unnamed: 0  Roll number      Name  Maths  Telugu  Science  Social  English
0           0          101       sai     90      87       90      70       89
1           1          102     manoj     98      67       87      89       78
2           2          103   pradeep     87      85       69      85       72
3           3          104      giri     67      93       90      92       83
4           4          105  vishnavi     78      92       89      78       94
5           5          106      teju     88      87       82      96       93

In [27]:
#DataFrames 11:
#data_frame iloc[]--- It will give the data of that row in the DataFrame
#About iloc: In python we learn,during indexing,stop index is not included, but in case  also  iloc,stop index is not included 
#as same as python indexing.

In [28]:
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df.iloc[0:10:1]

   Unnamed: 0  Roll number       Name  Maths  Telugu  Science  Social  English
0           0          101        sai     90      87       90      70       89
1           1          102      manoj     98      67       87      89       78
2           2          103    pradeep     87      85       69      85       72
3           3          104       giri     67      93       90      92       83
4           4          105   vishnavi     78      92       89      78       94
5           5          106       teju     88      87       82      96       93
6           6          107  teja sree     86      75       91      95       94
7           7          108       mahi     87      90       94      93       95
8           8          109       mani     80      97       95      94       96
9           9          110    charan      90      92       96      90       97

In [29]:
#Sorting the DataFrame:
#data_frame.sort_values('column_name')--- It will sort the data of that column
#Ascending order:ascending=True
#Descending order:ascending=False and vice versa.

In [30]:
#Sorting the DataFrame 1:
#data_frame.sort_values('column_name')--- It will sort the data of that column
#Ascending order:ascending=True
#Descending order:ascending=False and vice versa.

In [31]:
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df.sort_values('Maths',ascending=True)

,Unnamed: 0,Roll number,Name,Maths,Telugu,Science,Social,English
3,3,104,giri,67,93,90,92,83
18,18,119,keerthna,78,92,87,93,90
4,4,105,vishnavi,78,92,89,78,94
8,8,109,mani,80,97,95,94,96
16,16,117,kalyan,81,89,93,81,76
15,15,116,hari,82,85,72,99,74
17,17,118,revanth,83,96,91,82,67
6,6,107,teja sree,86,75,91,95,94
2,2,103,pradeep,87,85,69,85,72
7,7,108,mahi,87,90,94,93,95
5,5,106,teju,88,87,82,96,93
10,10,111,pavan,89,91,89,92,98
0,0,101,sai,90,87,90,70,89
9,9,110,charan,90,92,96,90,97
12,12,113,harsha,91,90,92,90,82
14,14,115,hemanth,93,87,90,82,72
13,13,114,bhuvi,94,90,90,87,93
11,11,112,kiran,98,76,93,89,99
1,1,102,manoj,98,67,87,89,78

In [32]:
#Sorting the DataFrame 2:
#data_frame.sort_values(['column1', 'column2'], ascending=[True, False])

In [33]:
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df.sort_values(['Social', 'Science'], ascending=[True, False])

,Unnamed: 0,Roll number,Name,Maths,Telugu,Science,Social,English
0,0,101,sai,90,87,90,70,89
4,4,105,vishnavi,78,92,89,78,94
16,16,117,kalyan,81,89,93,81,76
17,17,118,revanth,83,96,91,82,67
14,14,115,hemanth,93,87,90,82,72
2,2,103,pradeep,87,85,69,85,72
13,13,114,bhuvi,94,90,90,87,93
11,11,112,kiran,98,76,93,89,99
1,1,102,manoj,98,67,87,89,78
9,9,110,charan,90,92,96,90,97
12,12,113,harsha,91,90,92,90,82
3,3,104,giri,67,93,90,92,83
10,10,111,pavan,89,91,89,92,98
7,7,108,mahi,87,90,94,93,95
18,18,119,keerthna,78,92,87,93,90
8,8,109,mani,80,97,95,94,96
6,6,107,teja sree,86,75,91,95,94
5,5,106,teju,88,87,82,96,93
15,15,116,hari,82,85,72,99,74

In [34]:
#Sorting the DataFrame 3:
#data_frame.sort_values(['column1', 'column2'], ascending=[0, 1]
#This sorts the data, but does not permanently change dataframe.
#inplace=True → change the original DataFrame.
#inplace=False → don't change the original DataFrame.

In [35]:
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df.sort_values(['Telugu', 'English'], ascending=[1, 0])

,Unnamed: 0,Roll number,Name,Maths,Telugu,Science,Social,English
1,1,102,manoj,98,67,87,89,78
6,6,107,teja sree,86,75,91,95,94
11,11,112,kiran,98,76,93,89,99
15,15,116,hari,82,85,72,99,74
2,2,103,pradeep,87,85,69,85,72
5,5,106,teju,88,87,82,96,93
0,0,101,sai,90,87,90,70,89
14,14,115,hemanth,93,87,90,82,72
16,16,117,kalyan,81,89,93,81,76
7,7,108,mahi,87,90,94,93,95
13,13,114,bhuvi,94,90,90,87,93
12,12,113,harsha,91,90,92,90,82
10,10,111,pavan,89,91,89,92,98
9,9,110,charan,90,92,96,90,97
4,4,105,vishnavi,78,92,89,78,94
18,18,119,keerthna,78,92,87,93,90
3,3,104,giri,67,93,90,92,83
17,17,118,revanth,83,96,91,82,67
8,8,109,mani,80,97,95,94,96

In [36]:
#Sorting the DataFrame 4:
#data_frame.sort_values(['column1', 'column2'], ascending=[0, 1],inplace=True)
# This changes df directly.
#inplace=True → change the original DataFrame.
#inplace=False → don't change the original DataFrame.

In [37]:
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df.sort_values(['Telugu','English'], ascending=[1,0], inplace=True)

In [38]:
#MANIPULATING THE DATAFRAME:
#1. Adding a new column to the DataFrame: or Adding a new column to the DataFrame with default value:
#2.Removing a column from the DataFrame:
#3.Removing Duplicates from the DataFrame:

In [39]:
#1. Adding a new column to the DataFrame with default value:
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df['Total Marks']=default=0

In [40]:
df

,Unnamed: 0,Roll number,Name,Maths,Telugu,Science,Social,English,Total Marks
0,0,101,sai,90,87,90,70,89,0
1,1,102,manoj,98,67,87,89,78,0
2,2,103,pradeep,87,85,69,85,72,0
3,3,104,giri,67,93,90,92,83,0
4,4,105,vishnavi,78,92,89,78,94,0
5,5,106,teju,88,87,82,96,93,0
6,6,107,teja sree,86,75,91,95,94,0
7,7,108,mahi,87,90,94,93,95,0
8,8,109,mani,80,97,95,94,96,0
9,9,110,charan,90,92,96,90,97,0
10,10,111,pavan,89,91,89,92,98,0
11,11,112,kiran,98,76,93,89,99,0
12,12,113,harsha,91,90,92,90,82,0
13,13,114,bhuvi,94,90,90,87,93,0
14,14,115,hemanth,93,87,90,82,72,0
15,15,116,hari,82,85,72,99,74,0
16,16,117,kalyan,81,89,93,81,76,0
17,17,118,revanth,83,96,91,82,67,0
18,18,119,keerthna,78,92,87,93,90,0

In [41]:
#1. Adding a new column to the DataFrame :

In [42]:
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df['Total Marks']=df['Telugu']+df['English']+df['Maths']+df['Science']+df['Social']

In [43]:
df

,Unnamed: 0,Roll number,Name,Maths,Telugu,Science,Social,English,Total Marks
0,0,101,sai,90,87,90,70,89,426
1,1,102,manoj,98,67,87,89,78,419
2,2,103,pradeep,87,85,69,85,72,398
3,3,104,giri,67,93,90,92,83,425
4,4,105,vishnavi,78,92,89,78,94,431
5,5,106,teju,88,87,82,96,93,446
6,6,107,teja sree,86,75,91,95,94,441
7,7,108,mahi,87,90,94,93,95,459
8,8,109,mani,80,97,95,94,96,462
9,9,110,charan,90,92,96,90,97,465
10,10,111,pavan,89,91,89,92,98,459
11,11,112,kiran,98,76,93,89,99,455
12,12,113,harsha,91,90,92,90,82,445
13,13,114,bhuvi,94,90,90,87,93,454
14,14,115,hemanth,93,87,90,82,72,424
15,15,116,hari,82,85,72,99,74,412
16,16,117,kalyan,81,89,93,81,76,420
17,17,118,revanth,83,96,91,82,67,419
18,18,119,keerthna,78,92,87,93,90,440

In [44]:
#Removing a column from the DataFrame:
#Here we can use the Inplace=True or Inplace=False, 
#If we use inplace=True, then it will remove the column from the original DataFrame, 
#But if we use inplace=False, then it will not remove the column from the original DataFrame.

In [45]:
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df.drop(columns="Name")#Here i did not use inplace=True, so it will not remove the column from the original DataFrame.

    Unnamed: 0  Roll number  Maths  Telugu  Science  Social  English
0            0          101     90      87       90      70       89
1            1          102     98      67       87      89       78
2            2          103     87      85       69      85       72
3            3          104     67      93       90      92       83
4            4          105     78      92       89      78       94
5            5          106     88      87       82      96       93
6            6          107     86      75       91      95       94
7            7          108     87      90       94      93       95
8            8          109     80      97       95      94       96
9            9          110     90      92       96      90       97
10          10          111     89      91       89      92       98
11          11          112     98      76       93      89       99
12          12          113     91      90       92      90       82
13          13          114     94      90       90      87       93
14          14          115     93      87       90      82       72
15          15          116     82      85       72      99       74
16          16          117     81      89       93      81       76
17          17          118     83      96       91      82       67
18          18          119     78      92       87      93       90

In [46]:
#3. Removing Duplicates from the DataFrame:
#The Result of Duplicated() function is a Boolean Series,
#1.df.duplicated():This checks which rows are duplicates. It returns True or False.
#2.df.drop_duplicates():It removes duplicate rows

In [47]:
#1.df.duplicated():This checks which rows are duplicates. It returns True or False.
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df.duplicated()#The Result of Duplicated() function is a Boolean Series,
#Here we need to  write is Duplicated() not Duplicates().

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
dtype: bool

In [48]:
#2.df.drop_duplicates():It removes duplicate rows
import pandas as pd
df=pd.read_excel("//Users//charanreddy//Desktop//Marks First.xlsx")
df.drop_duplicates()#If i write df.drop_duplicates(Inplace=True), then it will remove the duplicate rows from the original DataFrame.

,Unnamed: 0,Roll number,Name,Maths,Telugu,Science,Social,English
0,0,101,sai,90,87,90,70,89
1,1,102,manoj,98,67,87,89,78
2,2,103,pradeep,87,85,69,85,72
3,3,104,giri,67,93,90,92,83
4,4,105,vishnavi,78,92,89,78,94
5,5,106,teju,88,87,82,96,93
6,6,107,teja sree,86,75,91,95,94
7,7,108,mahi,87,90,94,93,95
8,8,109,mani,80,97,95,94,96
9,9,110,charan,90,92,96,90,97
10,10,111,pavan,89,91,89,92,98
11,11,112,kiran,98,76,93,89,99
12,12,113,harsha,91,90,92,90,82
13,13,114,bhuvi,94,90,90,87,93
14,14,115,hemanth,93,87,90,82,72
15,15,116,hari,82,85,72,99,74
16,16,117,kalyan,81,89,93,81,76
17,17,118,revanth,83,96,91,82,67
18,18,119,keerthna,78,92,87,93,90

In [49]:
#Handling Missing Data:
#1.Data_Frame.drpna()--- It removes the rows with missing values.
#2.Data_Frame.dropna(inplace=True)--- It removes the rows with missing values from the original DataFrame.

In [50]:
#These is the  dataset with empty values in some of the rows and columns. 
import pandas as pd
df=pd.read_excel("/Users/charanreddy/Desktop/Farm Market.xlsx")
df

        Product       Country  Price($)  Quantity
0          Rice         india    2000.0      50.0
1        Tomato        Maxico       NaN    1000.0
2        Potato         India    1200.0     400.0
3         Beans           USA     400.0       NaN
4      Cilantro           USA      24.0      35.0
5  Thai Peppers      Thailand       NaN      25.0
6       Poultry        Europe    9000.0       NaN
7          Lamb         India   10000.0     500.0
8          Pork  South Africa    4500.0     349.0

In [51]:
## We can use dropna() function to remove those rows with empty values.
import pandas as pd
df=pd.read_excel("/Users/charanreddy/Desktop/Farm Market.xlsx")
df.dropna()

    Product       Country  Price($)  Quantity
0      Rice         india    2000.0      50.0
2    Potato         India    1200.0     400.0
4  Cilantro           USA      24.0      35.0
7      Lamb         India   10000.0     500.0
8      Pork  South Africa    4500.0     349.0

In [52]:
##2.Data_Frame.dropna(inplace=True)--- It removes the rows with missing values from the original DataFrame.
import pandas as pd
df=pd.read_excel("/Users/charanreddy/Desktop/Farm Market.xlsx")
df.dropna(inplace=True)

In [53]:
#Filling with default values:
import pandas as pd
df=pd.read_excel("/Users/charanreddy/Desktop/Farm Market.xlsx")
df.fillna(0)#Here we can fill the empty values with default value 0, but we can fill with any value.

        Product       Country  Price($)  Quantity
0          Rice         india    2000.0      50.0
1        Tomato        Maxico       0.0    1000.0
2        Potato         India    1200.0     400.0
3         Beans           USA     400.0       0.0
4      Cilantro           USA      24.0      35.0
5  Thai Peppers      Thailand       0.0      25.0
6       Poultry        Europe    9000.0       0.0
7          Lamb         India   10000.0     500.0
8          Pork  South Africa    4500.0     349.0

In [54]:
#Data Filling with Default Values and Condition:
#df.loc(simple condition)
#df.loc(compound condition)
#df.loc[df['simple_condition'].str.contains("value")]
#df.loc[df['simple_condition'].str.startswith("value")]
#df.loc[df['simple_condition'].str.endswith("value")]

In [55]:
#df.loc(simple condition)
import pandas as pd
df=pd.read_excel("/Users//charanreddy//Desktop//Marks First.xlsx")
df.loc[df['Maths']>90]

    Unnamed: 0  Roll number     Name  Maths  Telugu  Science  Social  English
1            1          102    manoj     98      67       87      89       78
11          11          112    kiran     98      76       93      89       99
12          12          113   harsha     91      90       92      90       82
13          13          114    bhuvi     94      90       90      87       93
14          14          115  hemanth     93      87       90      82       72

In [56]:
#df.loc(compound condition)
import pandas as pd
df=pd.read_excel("/Users//charanreddy//Desktop//Marks First.xlsx")
df.loc[(df['Telugu']>90) & (df['Science']>90)]

    Unnamed: 0  Roll number     Name  Maths  Telugu  Science  Social  English
8            8          109     mani     80      97       95      94       96
9            9          110  charan      90      92       96      90       97
17          17          118  revanth     83      96       91      82       67

In [57]:
#df.loc(df['simple_condition'].str.contains("value"))
import pandas as pd
df=pd.read_excel("/Users//charanreddy//Desktop//Marks First.xlsx")
df.loc[df['Name'].str.contains('j')]

   Unnamed: 0  Roll number       Name  Maths  Telugu  Science  Social  English
1           1          102      manoj     98      67       87      89       78
5           5          106       teju     88      87       82      96       93
6           6          107  teja sree     86      75       91      95       94

In [58]:
#df.loc[df['simple_condition'].str.startswith("value")]
import pandas as pd
df=pd.read_excel("/Users//charanreddy//Desktop//Marks First.xlsx")
df.loc[df['Name'].str.startswith('c')]

   Unnamed: 0  Roll number     Name  Maths  Telugu  Science  Social  English
9           9          110  charan      90      92       96      90       97

In [59]:
#df.loc['simple_condition'].str.endswith("vallue")]
import pandas as pd 
df=pd.read_excel("/Users//charanreddy//Desktop//Marks First.xlsx")
df.loc[df['Name'].str.endswith('a')]

    Unnamed: 0  Roll number      Name  Maths  Telugu  Science  Social  English
12          12          113    harsha     91      90       92      90       82
18          18          119  keerthna     78      92       87      93       90

In [60]:
#Yeah finnaly we completed the Pandas DataFrame Manipulations and Analysis.
#Exporting the DataFrame to Excel or CSV:
#df.to_excel("output.xlsx", index=False)Here index=False means we don't want to write row names (index).
#If we write index=True, then it will write row names (index) in the output file.
#AND
#df.to_csv("output.csv", index=False) or index=True, then it will write row names (index) in the output file.